projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: https://karma-panda.herokuapp.com/karma-panda-server/dev
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma.yml
